name: pdfviewer_plus
description: Flutter PDF Viewer library is used to display a PDF document seamlessly and efficiently.
version: 21.2.19
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdfviewer

environment:
  sdk: '>=3.0.3 <4.0.0'

flutter:

  plugin:
    platforms:
      android:
        package: com.syncfusion.flutter.pdfviewer
        pluginClass: SyncfusionFlutterPdfViewerPlugin
      ios:
        pluginClass: SyncfusionFlutterPdfViewerPlugin

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  async: ^2.11.0
  http: ^1.0.0
  uuid: ^3.0.7
  device_info_plus: ^9.0.2
  intl: ^0.18.0
  plugin_platform_interface: ^2.1.4

  # syncfusion_pdfviewer_platform_interface: ^21.2.10
  workspace_core:
    git:
      url: https://github.com/K1yoshiSho/workspace_flutter_core.git
      ref: main
  pdf_config:
    git:
      url: https://github.com/K1yoshiSho/pdf_config.git
      ref: main
  flutter_signaturepad:
    git:
      url: https://github.com/K1yoshiSho/flutter_signaturepad.git
      ref: main

  url_launcher: ^6.1.0

screenshots:
  - description: 'This screenshot shows the PdfViewer widget, which displays a PDF document.'
    path: screenshots/flutter-pdf-viewer.png
  - description: 'This screenshot shows the page navigation in the PdfViewer widget that is used to navigate to the desired page.'
    path: screenshots/flutter-pdf-viewer-page-navigation.png
  - description: 'This screenshot shows the bookmark navigation in the PdfViewer widget that is used to navigate to the desired bookmark.'
    path: screenshots/flutter-pdf-viewer-bookmark-navigation.png
  - description: 'This screenshot shows the selection and copying of text in the PdfViewer widget.'
    path: screenshots/flutter-pdf-viewer-text-selection.png
  - description: 'This screenshot shows the text search in the PdfViewer widget.'
    path: screenshots/flutter-pdf-viewer-text-search.png
  - description: 'This screenshot shows theme support in the PdfViewer widget.'
    path: screenshots/flutter-pdf-viewer-dark-theme.png
  - description: 'This screenshot shows the localization support in the PdfViewer widget.'
    path: screenshots/flutter-pdf-viewer-localization.png
